version: '3.8'

services:
  frontend:
    container_name: tekken-league-front
    networks:
      - tekken-league-network
    image: tekken-front
    ports:
      - "80:80"
    depends_on:
      - api
      - db
      - redis
    labels:
      "com.centurylinklabs.watchtower.enable": true
  api:
    container_name: tekken-league-api
    networks:
      - tekken-league-network
    image: tekken-back
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_URL=${DB_URL_DOCKER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - redis
    volumes:
      - ./:/node
      - /node/node_modules
    labels:
      "com.centurylinklabs.watchtower.enable": true
  redis:
    container_name: tekken-league-redis
    image: redis
    networks:
      - tekken-league-network
  db:
    container_name: tekken-league-db
    image: postgres:13-alpine
    networks:
      - tekken-league-network
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
networks:
  tekken-league-network:
    name: tekken-league-network