INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('AKUMA', 'Akuma', 'Акума');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('ALISA_BOSCONOVITCH', 'Alisa Bosconovitch', 'Алиса Босконович');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('ANNA_WILLIAMS', 'Anna Williams', 'Анна Виллиамс');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('ARMOR_KING', 'Armor King', 'Армор Кинг');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('ASUKA_KAZAMA', 'Asuka Kazama', 'Асука Казама');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('BOB_RICHARDS', 'Bob Richards', 'Боб Ричардс');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('BRYAN_FURY', 'Bryan Fury', 'Брайан Фьюри');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('CLAUDIO_SERAFINO', 'Claudio Serafino', 'Клаудио Серафино');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('CRAIG_MARDUK', 'Craig Marduk', 'Крэйг Мардук');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('DEVIL_JIN', 'Devil Jin', 'Девил Джин');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('EDDY_GORDO', 'Eddy Gordo', 'Эдди Гордо');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('ELIZA', 'Eliza', 'Элиза');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('FAHKUMRAM', 'Fahkumram', 'Факумрам');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('FENG_WEI', 'Feng Wei', 'Фенг Вэу');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('GANRYU', 'Ganryu', 'Ганрю');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('GEESE_HOWARD', 'Geese Howard', 'Гис Ховард');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('GIGAS', 'Gigas', 'Гигас');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('HEIHACHI_MISHIMA', 'Heihachi Mishima', 'Хейхачи Мишима');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('HWOARANG', 'Hwoarang', 'Хворанг');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('JACK-7', 'Jack-7', 'Джек-7');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('JIN_KAZAMA', 'Jin Kazama', 'Джин Казама');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('JOSIE_RIZAL', 'Josie Rizal', 'Джози Ризал');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('JULIA_CHANG', 'Julia Chang', 'Джулия Чан');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('KATARINA_ALVES', 'Katarina Alves', 'Катарина Алвес');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('KAZUMI_MISHIMA', 'Kazumi Mishima', 'Казуми Мишима');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('KAZUYA_MISHIMA', 'Kazuya Mishima', 'Казуя Мишима');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('KING', 'King', 'Кинг');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('KUMA', 'Kuma', 'Кума');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('KUNIMITSU', 'Kunimitsu', 'Кунимитсу');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LARS_ALEXANDERSSON', 'Lars Alexandersson', 'Ларс Александерссон');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LEE_CHAOLAN', 'Lee Chaolan', 'Ли Чаолан');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LEI_WULONG', 'Lei Wulong', 'Лей Вулон');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LEO_KLIESEN', 'Leo Kliesen', 'Лео Клисен ');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LEROY_SMITH', 'Leroy Smith', 'Лерой Смит');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LIDIA_SOBIESKA', 'Lidia Sobieska', 'Лидия Собеска');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LILI_DE_ROCHEFORT', 'Lili de Rochefort', 'Лили');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LING_XIAOYU', 'Ling Xiaoyu', 'Лин Сяоюй ');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('LUCKY_CHLOE', 'Lucky Chloe', 'Лаки Хлоя');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('MARSHALL_LAW', 'Marshall Law', 'Маршалл Ло');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('MASTER_RAVEN', 'Master Raven', 'Мастер Рейвен');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('MIGUEL', 'Miguel', 'Мигель');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('NEGAN', 'Negan', 'Ниган');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('NINA_WILLIAMS', 'Nina Williams', 'Нина Уильямс');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('NOCTIS', 'Noctis', 'Ноктис');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('PANDA', 'Panda', 'Панда');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('PAUL_PHOENIX', 'Paul Phoenix', 'Пол Феникс ');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('SERGEI_DRAGUNOV', 'Sergei Dragunov', 'Сергей Драгунов');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('SHAHEEN', 'Shaheen', 'Шахин');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('STEVE_FOX', 'Steve Fox', 'Стив Фокс');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('YOSHIMITSU', 'Yoshimitsu', 'Йошимитсу');
INSERT INTO d_characters(codename, label_en, label_ru) VALUES ('ZAFINA', 'Zafina', 'Зафина');